(* 1 2 3 4 5 (+ 1 2 3))
(def pi 3)
(list? (quote (1 2 3)))
(def if (m\ (expr true false)
    `(cond
        (#expr #true)
        (1     #false)
    )
))
(def id (.\ (x) x))
(if 1 2 '(1 2))
(id '(1 2 3))